"""Added metadata field in chat_records

Revision ID: 6dfb369adbd3
Revises: 1e0cf2fa6532
Create Date: 2024-04-26 10:49:47.821386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfb369adbd3'
down_revision = '1e0cf2fa6532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_records', schema=None) as batch_op:
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###
