"""updated the related_questions table

Revision ID: 7543dcc9f23b
Revises: 620a1ba6dead
Create Date: 2024-04-26 12:06:39.977176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7543dcc9f23b'
down_revision = '620a1ba6dead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_questions', schema=None) as batch_op:
        batch_op.drop_constraint('related_questions_ibfk_2', type_='foreignkey')
        batch_op.drop_column('related_question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('related_questions_ibfk_2', 'questions', ['related_question_id'], ['id'])

    # ### end Alembic commands ###
