"""Added User Table

Revision ID: 80e5e2baa1a7
Revises: f7b8ba059246
Create Date: 2024-04-26 16:35:03.685724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80e5e2baa1a7'
down_revision = 'f7b8ba059246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', mysql.INTEGER(
            display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(
            'questions_ibfk_1', 'answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###
